# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea2a1123ea3c4502a314cce4b4e1b1a8bfcaa6c3688f9260cf0afc84b6385e6fbb380310774b591b1bc2eb9e2d720dd15051b1cd66fca65748e1ffcd99ae6707

test:
  secret_key_base: a2f548378bf400983d3428d28865c67a43427575a917e2f1a9bdab0956bd52e8359c4a10504a9ca229e220dc9693f6a568a0e52f98458589e4ba122e03b241a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
